name: YouTube Data Collector

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write
  actions: read

jobs:
  collect_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install requests

      - name: Run Data Collection Script
        env:
          API_KEY: ${{ secrets.API_YOUTUBE }}
        run: python youtube_data_collector.py

      - name: Commit and Push Changes
        env:
          PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git pull --rebase origin main  # Ensure the latest changes are pulled
          git add youtube_trends.csv
          git commit -m "Updated YouTube Trends Data" || echo "No changes to commit"
          git push origin main
