name: YouTube Data Collector

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write
  actions: read

jobs:
  collect_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install requests

      - name: Debug API Key
        run: |
          if [[ -z "${API_YOUTUBE}" ]]; then
            echo "❌ ERROR: API_YOUTUBE secret is missing!"
            exit 1
          else
            echo "✅ API key detected!"
          fi
        env:
          API_YOUTUBE: ${{ secrets.API_YOUTUBE }}

      - name: Run Data Collection Script
        env:
          API_YOUTUBE: ${{ secrets.API_YOUTUBE }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: python youtube_data_collector.py

      - name: Commit and Push Changes
        env:
          PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git add youtube_trends.csv
          git commit -m "Updated YouTube Trends Data" || echo "No changes to commit"
          git push
